version: "3.8"

networks:
  stasher-network:
    driver: bridge
    ipam:
      driver: default

services:
  mysql:
    image: mysql
    container_name: mysql5
    restart: always
    ports:
      - "3310:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - stasher-network
    healthcheck:
      test: "/usr/bin/mysql --user=${DB_USER} --password=${DB_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
      
  rabbitmq:
    image: 'rabbitmq:3.7-management-alpine'
    container_name: rabbitmq
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
        - stasher-network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10 

  stasher-subscription-service:
    container_name: stasher-subscription-service
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: .
    command: [ "node", "-r", "newrelic", "index.js" ]
    ports:
      - "6061:6061"
    env_file: .env 
    networks:
      - stasher-network
    tty: true

  