version: "3.8"

networks:
  stasher-network:
    driver: bridge
    ipam:
      driver: default

services:
  mysql:
    image: mysql
    container_name: mysql2
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - stasher-network
    healthcheck:
      test: "/usr/bin/mysql --user=${DB_USER} --password=${DB_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
      
  redis: 
    image: redis
    container_name: cache
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    networks:
      - stasher-network

  stasher-expenses-service:
    container_name: stasher-expenses-service
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    build: .
    command: [ "node", "-r", "newrelic", "index.js" ]
    ports:
      - "6063:6063"
    env_file: .env 
    networks:
      - stasher-network
    tty: true

  