version: "3.8"

networks:
  stasher-network:
    driver: bridge
    ipam:
      driver: default

services:
  stasher-message-service:
    container_name: stasher-message-service
    build:
     context: app
     target: builder
    ports: 
      - '8001:8001'
    env_file: .env 
    networks:
      - stasher-network
    tty: true